version: '3.9'

services:
  web:
    # build: .
    image: singhh1/minimize-web:latest
    container_name: minimize-app
    ports:
      - "5001:5005"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://pgauser:hs@db:5432/minimize-db
    volumes:
      - /home/ubuntu/static:/app/static

  db:
    image: postgres
    container_name: dplocal_pgdb
    restart: always
    # ports:
    #   - "5433:5432"
    environment:
      POSTGRES_USER: pgauser
      POSTGRES_PASSWORD: hs
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: dppgadmin4_container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: singh.himanshup@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hs
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  static-data:
