"""added nickname

Revision ID: 083edcbda50f
Revises: 686a39c586ae
Create Date: 2025-02-17 15:22:35.636842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083edcbda50f'
down_revision = '686a39c586ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
