"""Added Verification Column

Revision ID: 32427a00d2e9
Revises: 6adc20dbbb83
Create Date: 2025-03-28 16:55:09.150629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32427a00d2e9'
down_revision = '6adc20dbbb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
