"""inital creation

Revision ID: 686a39c586ae
Revises: 
Create Date: 2025-02-17 15:18:35.982944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686a39c586ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep', sa.String(length=15), nullable=False),
    sa.Column('cleanliness', sa.String(length=15), nullable=False),
    sa.Column('relationship', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_handle', sa.String(length=50), nullable=True),
    sa.Column('snapchat_handle', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=100), nullable=False),
    sa.Column('short_bio', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_socials')
    op.drop_table('user_habits')
    op.drop_table('user')
    # ### end Alembic commands ###
