"""Added Image Row to Item table

Revision ID: b582c21ae46b
Revises: 7fd2b023b234
Create Date: 2025-02-28 10:46:11.533705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b582c21ae46b'
down_revision = '7fd2b023b234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.drop_column('item_image')

    # ### end Alembic commands ###
